on:
  issues:
    types: [labeled]
jobs:
  main:
    runs-on: self-hosted
    steps:

      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Label check
      if: contains(github.event.issue.labels.*.name, 'cont')
      run: echo YES IS CONT
