on:
  issues:
    types: [labeled]
jobs:
  main:
    if: github.event.label.name == 'cont'
    runs-on: self-hosted
    steps:

    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
