---
on:
  workflow_dispatch:
  issues:
    types: [labeled]
jobs:
  main:
    if: github.event.label.name == 'cont'
    runs-on: self-hosted
    env:
      LABEL: "cont"
    steps:

      - name: pre
        run: jq . "$GITHUB_EVENT_PATH"

      - name: Authenticate gh to repo
        id: auth_gh
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Clean working area and clone repo
        id: clean_clone
        run: |
          rm -rf ${{ github.event.repository.name }}
          gh repo clone ${{ github.repository }}

      - name: Count number of times label has been added
        id: count_add
        run: |
          endpoint="repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/events"
          count=$(gh api --jq "[.[]|(select(.event==\"labeled\" and .label.name==\"$LABEL\"))] | length" $endpoint)
          echo "EVENTCOUNT=$count" >> $GITHUB_ENV

      - name: Check env
        run: env

      - name: MAIN0003
        if: env.EVENTCOUNT == 1
        run: echo OK
