---
on:
  workflow_dispatch:
  issues:
    types: [labeled]
jobs:
  main:
    if: github.event.label.name == 'cont'
    runs-on: self-hosted
    steps:

      - name: MAIN0001
        run: |
          apiendpoint="repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/events"
          echo "EVENTCOUNT=$(gh api --jq '[.[] | (select( .event == "labeled" and .label.name == "cont"))] | length' $apiendpoint)" >> $GITHUB_ENV

      - name: MAIN0002
        run: env

      - name: MAIN0003
        if: env.EVENTCOUNT == 1
        run: echo OK
