---
on:
  workflow_dispatch:
  issues:
    types: [labeled]
jobs:
  main:
    if: github.event.label.name == 'cont'
    runs-on: self-hosted
    steps:

      - name: MAIN0001
        run: |
          contlabelevents=$(
            gh api --jq '[.[] | (select( .event == "labeled" and .label.name == "cont"))] | length' \
              /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/events
          )
          echo "$CODOC_CONTLABELEVENTS=$contlabelevents" >> $GITHUB_ENV

      - name: MAIN0002
        run: env

      - name: MAIN0003
        id: MYID0002
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
