---
on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  issues:
    types: [labeled]

jobs:

  community-id-requester:
    env:
      LABEL: "cont"
    runs-on: ubuntu-20.04
    if: github.event.label.name == 'cont'

    steps:

      - id: auth_gh
        name: Authenticate gh to repo
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - id: clean_clone
        name: Clean working area and clone repo
        run: |
          rm -rf ${{ github.event.repository.name }}
          gh repo clone ${{ github.repository }}

      - id: count_label_additions
        name: Count number of times label has been added
        run: |
          objectnr=${{ github.event.issue.number || github.event.pull_request.number }}
          endpoint="repos/${{ github.repository }}/issues/$objectnr/events"
          count=$(gh api --jq "[.[]|(select(.event==\"labeled\" and .label.name==\"$LABEL\"))] | length" $endpoint)
          echo "LABELADDITIONCOUNT=$count" >> $GITHUB_ENV

      - id: requester
        name: Ask for SAP Community profile URL if label added for first time
        if: env.LABELADDITIONCOUNT == 1
        working-directory: ${{ github.event.repository.name }}
        run: |
          printf "Thank you for your valuable contribution, @${{ github.event.issue.user.login }}! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:\n\n\`\`\`\nhttps://people.sap.com/your-user-id\n\`\`\`\n\nThanks!" | gh issue comment ${{ github.event.issue.number }} --body-file -
