on:
  issues:
    types: [labeled]
jobs:
  main:
    runs-on: self-hosted
    steps:

    - name: Show context
      run: echo ${{ toJSON(github) }}

    - name: Label check
      if: contains(github.event.issue.labels.*.name, 'cont')
      run: echo YES IS CONT
