---
on:
  pull_request:
    types: [closed]

jobs:

  assign-label-on-merge:
    if: github.event.pull_request.merged
    env:
      LABEL: "cont"
    runs-on: ubuntu-20.04

    steps:
      - id: env
        env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo "$CONTEXT"

      - id: auth_gh
        name: Authenticate gh to repo
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - id: clean_clone
        name: Clean working area and clone repo
        run: |
          rm -rf ${{ github.event.repository.name }}
          gh repo clone ${{ github.repository }}

      - id: assign_label
        run: gh pr edit ${{ github.event.number }} --add-label "$LABEL"
        working-directory: ${{ github.event.repository.name }}
