---
on:
  workflow_dispatch:
  issues:
    types: [labeled]
jobs:
  main:
    if: github.event.label.name == 'cont'
    runs-on: self-hosted
    steps:

      - name: gh version
        run: gh --version

      - name: Events
        run: |
          gh api /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/events

      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
