---
on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  issues:
    types: [labeled]
jobs:
  main:
    runs-on: self-hosted
    env:
      LABEL: "cont"
    if: github.event.label.name == ${{ env.LABEL }}
    steps:

      - name: pre
        run: jq . "$GITHUB_EVENT_PATH"

      - name: Authenticate gh to repo
        id: auth_gh
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Clean working area and clone repo
        id: clean_clone
        run: |
          rm -rf ${{ github.event.repository.name }}
          gh repo clone ${{ github.repository }}

      - name: Count number of times label has been added
        id: count_add
        run: |
          objectnr=${{ github.event.issue.number || github.event.pull_request.number }}
          endpoint="repos/${{ github.repository }}/issues/$objectnr/events"
          count=$(gh api --jq "[.[]|(select(.event==\"labeled\" and .label.name==\"$LABEL\"))] | length" $endpoint)
          echo "EVENTCOUNT=$count" >> $GITHUB_ENV

      - name: Ask for SAP Community profile URL
        id: community_profile
        if: env.EVENTCOUNT == 1
        working-directory: ${{ github.event.repository.name }}
        run: |
          printf "Thank you for your valuable contribution, @${{ github.event.issue.user.login }}! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:\n\n\`\`\`\nhttps://people.sap.com/your-user-id\n\`\`\`\n\nThanks!" | gh issue comment ${{ github.event.issue.number }} --body-file -
